---
# ArgoCD Self-Management Application
# This allows ArgoCD to manage its own configuration via GitOps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Update with your GitOps repo
    repoURL: https://github.com/your-org/your-repo.git
    path: gitops/bootstrap/overlays/staging  # Change to production for prod env
    targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: false  # Be careful with self-management
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false  # Namespace already exists
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
